// apps/team-react/src/App.tsx
import { useState, useEffect, useCallback } from 'react';
import type { User, FeatureFlags } from './types';
import type { FieldError } from '@poc/validators';
import { validate, createUserSchema } from './validation';
import { api } from './api';
import { Button } from '@poc/ui-components/react';

// ── App ───────────────────────────────────────────────────────────────────────

export default function App() {
  const [flags, setFlags] = useState<Partial<FeatureFlags>>({});

  // Load flags once on mount — every component reads from this shared state
  useEffect(() => {
    api.getFlags()
      .then(f => setFlags(f))
      .catch(() => {/* gateway not yet up — keep empty defaults */});
  }, []);

  const dark        = !!flags.UI_DARK_MODE;
  const maintenance = !!flags.CORE_MAINTENANCE_MODE;

  return (
    <div className={`app${dark ? ' dark' : ''}`}>
      <header className="app-header">
        <h1>Team React App</h1>
        <span className="badge">React 18 + Vite</span>
        {dark && <span className="badge badge-dark">🌙 Dark Mode ON</span>}
        {maintenance && <span className="badge badge-maint">🔧 Maintenance</span>}
      </header>

      <div className="tag-row">
        <span className="tag">@poc/types</span>
        <span className="tag">@poc/validators</span>
        <span className="tag">@poc/api-client</span>
        <span className="tag">@poc/feature-flags</span>
      </div>

      {/* ── CORE_MAINTENANCE_MODE ─────────────────────────────────────────── */}
      {maintenance && (
        <div className="maintenance-banner">
          <span className="maint-icon">🔧</span>
          <div>
            <strong>Platform under maintenance — CORE_MAINTENANCE_MODE: true</strong>
            <p>Write operations are disabled. Read-only access is still available.</p>
            <code>packages/feature-flags/src/flags.ts → CORE_MAINTENANCE_MODE: false to restore</code>
          </div>
        </div>
      )}

      {/* ── USER_SELF_REGISTRATION gates the create-user form ─────────────── */}
      {flags.USER_SELF_REGISTRATION !== false ? (
        <CreateUserForm disabled={maintenance} />
      ) : (
        <div className="card flag-blocked">
          <span className="flag-blocked-icon">🚫</span>
          <div>
            <strong>USER_SELF_REGISTRATION: OFF — Create User form is hidden</strong>
            <p>Set <code>USER_SELF_REGISTRATION: true</code> in <code>packages/feature-flags/src/flags.ts</code> to re-enable.</p>
          </div>
        </div>
      )}

      {/* ── User list (flags control layout + columns) ────────────────────── */}
      <UserList flags={flags} />

      {/* ── Feature flags panel ───────────────────────────────────────────── */}
      <FeatureFlagsPanel flags={flags} onLoad={setFlags} />

      {/* ── UI_QUICK_ACTIONS_BAR — floating toolbar ───────────────────────── */}
      {flags.UI_QUICK_ACTIONS_BAR && (
        <div className="quick-actions-bar">
          <span className="qa-label">⚡ Quick Actions</span>
          <Button size="sm" className="qa-btn" disabled={maintenance}>+ User</Button>
          <Button size="sm" className="qa-btn">📋 Export</Button>
          <Button size="sm" className="qa-btn">🔔 Notify</Button>
          <span className="qa-flag">UI_QUICK_ACTIONS_BAR: ON</span>
        </div>
      )}
    </div>
  );
}

// ── Create User Form ──────────────────────────────────────────────────────────

function CreateUserForm({ disabled }: { disabled?: boolean }) {
  const [fields, setFields] = useState({ email: '', password: '', firstName: '', lastName: '' });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [status, setStatus] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [loading, setLoading] = useState(false);

  function set(k: keyof typeof fields) {
    return (e: React.ChangeEvent<HTMLInputElement>) => {
      setFields(prev => ({ ...prev, [k]: e.target.value }));
      setErrors(prev => { const n = { ...prev }; delete n[k]; return n; });
    };
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (disabled) return;
    setStatus(null);

    // ── CLIENT-SIDE VALIDATION using @poc/validators ────────────────────────
    // The EXACT same Zod schema runs here in the browser AND in user-service.
    // If the schema changes, both sides stay in sync automatically.
    const result = validate(createUserSchema, fields);
    if (!result.success) {
      const map: Record<string, string> = {};
      result.errors.forEach((err: FieldError) => { map[err.field] = err.message; });
      setErrors(map);
      return;
    }

    setLoading(true);
    try {
      await api.createUser({
        email: result.data!.email,
        password: result.data!.password,
        firstName: result.data!.firstName,
        lastName: result.data!.lastName,
      });
      setStatus({ type: 'success', text: `✅ User "${fields.firstName} ${fields.lastName}" created! Same Zod schema validated both client + server.` });
      setFields({ email: '', password: '', firstName: '', lastName: '' });
    } catch (err: unknown) {
      setStatus({ type: 'error', text: err instanceof Error ? err.message : 'Create failed' });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="card">
      <h2>Create User — Shared Validation (<code>@poc/validators</code>)</h2>
      <p style={{ fontSize: '0.85rem', color: '#718096', marginBottom: '1rem' }}>
        Client-side Zod schema = server-side schema. Zero duplication.{' '}
        Password requires: <strong>8+ chars · 1 uppercase · 1 number · 1 symbol</strong>
        {disabled && <span style={{ color: '#c53030', marginLeft: '0.5rem' }}>⚠️ Disabled — maintenance mode</span>}
      </p>

      {status && <div className={`alert alert-${status.type}`}>{status.text}</div>}

      <form onSubmit={submit} style={{ opacity: disabled ? 0.6 : 1 }}>
        <div className="form-grid">
          <div className="field">
            <label>First Name</label>
            <input value={fields.firstName} onChange={set('firstName')} disabled={disabled}
              className={errors.firstName ? 'error' : ''} placeholder="Alice" />
            {errors.firstName && <span className="err">{errors.firstName}</span>}
          </div>
          <div className="field">
            <label>Last Name</label>
            <input value={fields.lastName} onChange={set('lastName')} disabled={disabled}
              className={errors.lastName ? 'error' : ''} placeholder="Chen" />
            {errors.lastName && <span className="err">{errors.lastName}</span>}
          </div>
          <div className="field">
            <label>Email</label>
            <input type="email" value={fields.email} onChange={set('email')} disabled={disabled}
              className={errors.email ? 'error' : ''} placeholder="alice@example.com" />
            {errors.email && <span className="err">{errors.email}</span>}
          </div>
          <div className="field">
            <label>Password</label>
            <input type="password" value={fields.password} onChange={set('password')} disabled={disabled}
              className={errors.password ? 'error' : ''} placeholder="e.g. Secret1!" />
            {errors.password && <span className="err">{errors.password}</span>}
          </div>
        </div>
        <div className="btn-row">
          <Button type="submit" variant="primary" disabled={loading || disabled} loading={loading}>
            {loading ? 'Creating…' : 'Create User'}
          </Button>
          {disabled && <span style={{ fontSize: '0.8rem', color: '#a0aec0' }}>Unlock: set CORE_MAINTENANCE_MODE: false</span>}
        </div>
      </form>
    </div>
  );
}

// ── User List ─────────────────────────────────────────────────────────────────

function UserList({ flags }: { flags: Partial<FeatureFlags> }) {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const result = await api.getUsers();
      setUsers(result.items);
      setError(null);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to load users');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { void load(); }, [load]);

  const bulkOps  = !!flags.ORDER_BULK_OPERATIONS;
  const cardView = !!flags.UI_NEW_DASHBOARD_LAYOUT;
  const avatars  = !!flags.USER_PROFILE_PICTURE;

  function toggleSelect(id: string) {
    setSelected(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem', flexWrap: 'wrap', gap: '0.5rem' }}>
        <h2 style={{ margin: 0 }}>Users — <code>@poc/types</code></h2>
        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', flexWrap: 'wrap' }}>
          {cardView  && <span className="flag-badge flag-on-badge">📊 UI_NEW_DASHBOARD_LAYOUT</span>}
          {bulkOps   && <span className="flag-badge flag-on-badge">☑️ ORDER_BULK_OPERATIONS</span>}
          {avatars   && <span className="flag-badge flag-on-badge">🖼 USER_PROFILE_PICTURE</span>}
            <Button variant="ghost" onClick={load} disabled={loading}>↻ Refresh</Button>
        </div>
      </div>

      {bulkOps && selected.size > 0 && (
        <div className="bulk-actions-bar">
          <span>{selected.size} user(s) selected</span>
            <Button variant="ghost" size="sm">Suspend selected</Button>
            <Button variant="ghost" size="sm" style={{ color: '#c53030' }}>Delete selected</Button>
            <Button variant="ghost" size="sm" onClick={() => setSelected(new Set())}>Clear</Button>
        </div>
      )}

      {error && <div className="alert alert-error">{error}</div>}

      {loading ? (
        <div className="loading">Loading users…</div>
      ) : cardView ? (
        /* ── UI_NEW_DASHBOARD_LAYOUT: card grid ────────────────────────────── */
        <div className="user-card-grid">
          {users.map(u => (
            <div key={u.id} className="user-card">
              {avatars && (
                <div className="avatar">{u.firstName[0]}{u.lastName[0]}</div>
              )}
              <div className="user-card-info">
                <strong>{u.firstName} {u.lastName}</strong>
                <span className="user-card-email">{u.email}</span>
                <div style={{ display: 'flex', gap: '0.4rem', marginTop: '0.35rem' }}>
                  <span className={`role-badge role-${u.role.toLowerCase()}`}>{u.role}</span>
                  <span className={`status-dot dot-${u.status.toLowerCase()}`}></span>
                  <span style={{ fontSize: '0.75rem', color: '#718096' }}>{u.status}</span>
                </div>
              </div>
              {bulkOps && (
                <input type="checkbox" className="bulk-check"
                  checked={selected.has(u.id)} onChange={() => toggleSelect(u.id)} />
              )}
            </div>
          ))}
        </div>
      ) : (
        /* ── Default table layout ─────────────────────────────────────────── */
        <table className="user-table">
          <thead>
            <tr>
              {bulkOps && <th style={{ width: '2rem' }}></th>}
              {avatars && <th style={{ width: '2.5rem' }}></th>}
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Status</th>
              <th>Created</th>
            </tr>
          </thead>
          <tbody>
            {users.map(u => (
              <tr key={u.id} className={selected.has(u.id) ? 'row-selected' : ''}>
                {bulkOps && (
                  <td>
                    <input type="checkbox" checked={selected.has(u.id)} onChange={() => toggleSelect(u.id)} />
                  </td>
                )}
                {avatars && (
                  <td>
                    <div className="avatar avatar-sm">{u.firstName[0]}{u.lastName[0]}</div>
                  </td>
                )}
                <td>{u.firstName} {u.lastName}</td>
                <td>{u.email}</td>
                <td><span className={`role-badge role-${u.role.toLowerCase()}`}>{u.role}</span></td>
                <td>
                  <span className={`status-dot dot-${u.status.toLowerCase()}`}></span>
                  {u.status}
                </td>
                <td>{new Date(u.createdAt).toLocaleDateString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

// ── Feature Flags Panel ───────────────────────────────────────────────────────

const FLAG_EFFECTS: Partial<Record<keyof FeatureFlags, string>> = {
  CORE_MAINTENANCE_MODE:    'Red banner, disables write ops',
  USER_SELF_REGISTRATION:   'Show/hide Create User form',
  USER_ROLE_MANAGER_ENABLED:'Show/hide MANAGER badges (Angular)',
  USER_PROFILE_PICTURE:     'Show avatar initials in user rows',
  ORDER_BULK_OPERATIONS:    'Add checkbox column + bulk-action bar',
  UI_DARK_MODE:             'Apply .dark class to root element',
  UI_NEW_DASHBOARD_LAYOUT:  'Switch user list to card grid',
  UI_QUICK_ACTIONS_BAR:     'Floating quick-actions toolbar',
};

function FeatureFlagsPanel({
  flags,
  onLoad,
}: {
  flags: Partial<FeatureFlags>;
  onLoad: (f: Partial<FeatureFlags>) => void;
}) {
  const [loading, setLoading] = useState(Object.keys(flags).length === 0);

  useEffect(() => {
    if (Object.keys(flags).length > 0) { setLoading(false); return; }
    api.getFlags()
      .then(f => { onLoad(f); setLoading(false); })
      .catch(() => setLoading(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="card">
      <h2>Feature Flags — <code>@poc/feature-flags</code> via api-gateway</h2>
      <p style={{ fontSize: '0.85rem', color: '#718096', marginBottom: '1rem' }}>
        Toggle flags in <code>packages/feature-flags/src/flags.ts</code> and restart the gateway. Each flag below lists its <strong>actual UI effect</strong> in this app.
      </p>
      {loading ? (
        <div className="loading">Loading flags…</div>
      ) : (
        <div className="flag-grid">
          {(Object.entries(flags) as [keyof FeatureFlags, boolean][]).map(([k, v]) => (
            <div key={k} className={`flag-item${v ? ' flag-item-on' : ''}`}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontFamily: 'monospace', fontWeight: 600 }}>{k}</span>
                <span className={v ? 'flag-on' : 'flag-off'}>{v ? 'ON' : 'OFF'}</span>
              </div>
              {FLAG_EFFECTS[k] && (
                <div style={{ fontSize: '0.7rem', color: '#718096', marginTop: '0.2rem' }}>
                  {v ? '↳ ' : '✗ '}{FLAG_EFFECTS[k]}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// apps/team-angular/src/app/app.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import type { User, PaginatedResponse, ApiResponse } from '@poc/types';
import { UserRole, UserStatus } from '@poc/types';
import { getFlag } from '@poc/feature-flags';
import type { FeatureFlags } from '@poc/feature-flags';
import {
  ButtonComponent,
  CardComponent,
  BadgeComponent,
  StatusIndicatorComponent,
} from '@poc/ui-components';
import type { BadgeColor, StatusLevel } from '@poc/ui-components';

// ─── API service ──────────────────────────────────────────────────────────────
const API_BASE = 'http://localhost:3000';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule, ButtonComponent, CardComponent, BadgeComponent, StatusIndicatorComponent],
  template: `
    <div class="app" [class.dark]="darkMode">
      <header class="app-header">
        <h1>Team Angular App</h1>
        <poc-badge color="purple">Angular 18</poc-badge>
        <poc-badge color="blue">Standalone</poc-badge>
        <poc-badge *ngIf="darkMode" color="blue">🌙 Dark Mode ON</poc-badge>
        <poc-badge *ngIf="maintenanceMode" color="red">🔧 Maintenance</poc-badge>
      </header>

      <div class="tag-row">
        <span class="tag">&#64;poc/types</span>
        <span class="tag">&#64;poc/ui-components</span>
        <span class="tag">&#64;poc/api-client</span>
        <span class="tag">&#64;poc/feature-flags</span>
      </div>

      <!-- CORE_MAINTENANCE_MODE banner ───────────────────────────────────── -->
      <div *ngIf="maintenanceMode" class="maintenance-banner">
        <span class="maint-icon">🔧</span>
        <div>
          <strong>Platform under maintenance — CORE_MAINTENANCE_MODE: true</strong>
          <p>Write operations are disabled. Set <code>CORE_MAINTENANCE_MODE: false</code> in
             <code>packages/feature-flags/src/flags.ts</code> to restore.</p>
        </div>
      </div>

      <!-- Feature flag status panel ──────────────────────────────────────── -->
      <poc-card title="Feature Flags — Live from @poc/feature-flags" subtitle="These flags are fetched from the api-gateway on startup and gate real UI sections below" [bordered]="true">
        <div class="flag-status-grid">
          <div *ngFor="let entry of flagEntries" class="flag-status-item" [class.flag-item-on]="entry.value">
            <span class="flag-name">{{ entry.key }}</span>
            <span [class]="entry.value ? 'flag-on' : 'flag-off'">{{ entry.value ? 'ON' : 'OFF' }}</span>
            <span *ngIf="flagEffects[entry.key]" class="flag-effect">
              {{ entry.value ? '↳ ' : '✗ ' }}{{ flagEffects[entry.key] }}
            </span>
          </div>
        </div>
      </poc-card>

      <!-- Users section ──────────────────────────────────────────────────── -->
      <poc-card
        [title]="'Order Admins' + (!managerRoleEnabled ? ' (MANAGER rows hidden — USER_ROLE_MANAGER_ENABLED: OFF)' : '')"
        subtitle="Typed with @poc/types · User.role, User.status from packages/types/src/user.types.ts"
        [bordered]="true" [elevated]="true">

        <div *ngIf="loading" class="loading">Loading users…</div>
        <div *ngIf="error" class="alert-error">{{ error }}</div>

        <table *ngIf="!loading && filteredUsers.length" class="user-table">
          <thead>
            <tr>
              <th *ngIf="showAvatars" style="width:2.5rem"></th>
              <th>Name</th>
              <th>Role</th>
              <th>Status</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let user of filteredUsers">
              <td *ngIf="showAvatars">
                <div class="avatar">{{ user.firstName[0] }}{{ user.lastName[0] }}</div>
              </td>
              <td>{{ user.firstName }} {{ user.lastName }}</td>
              <td>
                <poc-badge [color]="roleBadgeColor(user.role)">{{ user.role }}</poc-badge>
              </td>
              <td>
                <poc-status-indicator [status]="statusLevel(user.status)" [label]="user.status"></poc-status-indicator>
              </td>
              <td style="color: #718096; font-size: 0.875rem">{{ user.email }}</td>
            </tr>
          </tbody>
        </table>

        <div *ngIf="!managerRoleEnabled && !loading" class="flag-note">
          🚫 <strong>USER_ROLE_MANAGER_ENABLED: OFF</strong> — {{ hiddenManagerCount }} MANAGER row(s) are hidden.
          Set it to <code>true</code> to show them.
        </div>

        <div [attr.slot]="'footer'" *ngIf="!loading">
          <poc-button variant="ghost" (click)="loadUsers()">↻ Refresh</poc-button>
          <span style="margin-left:1rem; font-size:0.8rem; color:#a0aec0">
            {{ filteredUsers.length }} / {{ users.length }} user(s) shown via &#64;poc/api-client
          </span>
        </div>
      </poc-card>

      <!-- UI_QUICK_ACTIONS_BAR ───────────────────────────────────────────── -->
      <div *ngIf="quickActionsBar" class="quick-actions-bar">
        <span class="qa-label">⚡ Quick Actions</span>
        <button class="qa-btn" [disabled]="maintenanceMode">+ User</button>
        <button class="qa-btn">📋 Export</button>
        <button class="qa-btn">🔔 Notify</button>
        <span class="qa-flag">UI_QUICK_ACTIONS_BAR: ON</span>
      </div>

      <!-- Components showcase ─────────────────────────────────────────────── -->
      <poc-card title="Shared UI Components — @poc/ui-components" subtitle="ButtonComponent, CardComponent, BadgeComponent, StatusIndicatorComponent" [bordered]="true">
        <div class="component-row">
          <poc-button variant="primary">Primary</poc-button>
          <poc-button variant="secondary">Secondary</poc-button>
          <poc-button variant="danger">Danger</poc-button>
          <poc-button variant="ghost">Ghost</poc-button>
          <poc-button variant="primary" [loading]="true">Loading</poc-button>
          <poc-button variant="primary" [disabled]="true">Disabled</poc-button>
        </div>
        <div class="component-row" style="margin-top:1rem">
          <poc-badge color="blue">ADMIN</poc-badge>
          <poc-badge color="green">ACTIVE</poc-badge>
          <poc-badge color="red">SUSPENDED</poc-badge>
          <poc-badge color="yellow">PENDING</poc-badge>
          <poc-badge color="purple">MANAGER</poc-badge>
          <poc-badge color="gray">INACTIVE</poc-badge>
        </div>
        <div class="component-row" style="margin-top:1rem">
          <poc-status-indicator status="success" label="Service healthy" [pulse]="true"></poc-status-indicator>
          <poc-status-indicator status="warning" label="High latency"></poc-status-indicator>
          <poc-status-indicator status="error" label="Service down"></poc-status-indicator>
          <poc-status-indicator status="info" label="Updating"></poc-status-indicator>
        </div>
      </poc-card>
    </div>
  `,
  styles: [`
    .app { max-width: 1100px; margin: 0 auto; padding: 2rem 1.5rem; }
    .app.dark { background: #1a202c; color: #e2e8f0; min-height: 100vh; }
    .app.dark poc-card { --card-bg: #2d3748; --card-border: #4a5568; }
    .app-header { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 1.5rem;
                  padding-bottom: 1.5rem; border-bottom: 2px solid #e2e8f0; flex-wrap: wrap; }
    .app-header h1 { font-size: 1.5rem; font-weight: 700; margin-right: 0.25rem; }
    .dark .app-header { border-color: #4a5568; }
    .tag-row { display: flex; gap: 0.5rem; flex-wrap: wrap; margin-bottom: 1.5rem; }
    .tag { background: #edf2f7; color: #4a5568; font-size: 0.75rem; font-weight: 600;
           padding: 0.2rem 0.6rem; border-radius: 0.25rem; font-family: monospace; }
    poc-card { display: block; margin-bottom: 1.5rem; }
    .loading { padding: 1rem; color: #a0aec0; }
    .alert-error { padding: 0.75rem; background: #fff5f5; color: #c53030;
                   border-radius: 0.375rem; border: 1px solid #fed7d7; }
    .user-table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
    .user-table th { text-align: left; font-size: 0.7rem; font-weight: 700;
                     text-transform: uppercase; letter-spacing: 0.05em; color: #718096;
                     padding: 0.5rem 0.75rem; border-bottom: 2px solid #e2e8f0; }
    .user-table td { padding: 0.6rem 0.75rem; border-bottom: 1px solid #f7fafc; }
    .component-row { display: flex; gap: 0.75rem; flex-wrap: wrap; align-items: center; }

    /* maintenance banner */
    .maintenance-banner { display: flex; gap: 1rem; align-items: flex-start;
      background: #fff5f5; border: 1px solid #fc8181; border-left: 4px solid #e53e3e;
      border-radius: 0.375rem; padding: 1rem 1.25rem; margin-bottom: 1.5rem; color: #742a2a; }
    .maintenance-banner p { margin: 0.25rem 0 0; font-size: 0.85rem; }
    .maint-icon { font-size: 1.5rem; flex-shrink: 0; }

    /* flag status grid */
    .flag-status-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(230px, 1fr)); gap: 0.5rem; }
    .flag-status-item { display: flex; flex-direction: column; padding: 0.5rem 0.75rem;
                        background: #f7fafc; border-radius: 0.375rem; font-size: 0.8rem; }
    .flag-item-on { background: #f0fff4 !important; border: 1px solid #c6f6d5; }
    .flag-name { font-family: monospace; font-weight: 600; }
    .flag-on { color: #276749; font-weight: 700; font-size: 0.75rem; }
    .flag-off { color: #a0aec0; font-size: 0.75rem; }
    .flag-effect { font-size: 0.7rem; color: #718096; margin-top: 0.1rem; }
    .flag-note { padding: 0.75rem; background: #fffff0; border: 1px dashed #d69e2e;
                 border-radius: 0.375rem; color: #744210; font-size: 0.85rem; margin-top: 0.75rem; }

    /* avatar */
    .avatar { width: 1.75rem; height: 1.75rem; border-radius: 50%;
      background: linear-gradient(135deg, #4299e1, #667eea); color: #fff;
      font-weight: 700; font-size: 0.65rem; display: flex; align-items: center;
      justify-content: center; text-transform: uppercase; }

    /* quick actions bar */
    .quick-actions-bar { position: fixed; bottom: 1.5rem; right: 1.5rem;
      display: flex; align-items: center; gap: 0.5rem;
      background: #2d3748; color: #e2e8f0; border-radius: 9999px;
      padding: 0.5rem 1.25rem; box-shadow: 0 4px 16px rgba(0,0,0,0.2); z-index: 1000; font-size: 0.85rem; }
    .qa-label { font-weight: 700; margin-right: 0.25rem; }
    .qa-btn { background: rgba(255,255,255,0.1); border: none; color: #e2e8f0;
      padding: 0.25rem 0.75rem; border-radius: 9999px; cursor: pointer; font-size: 0.8rem; }
    .qa-btn:hover:not(:disabled) { background: rgba(255,255,255,0.2); }
    .qa-btn:disabled { opacity: 0.4; cursor: not-allowed; }
    .qa-flag { font-size: 0.65rem; opacity: 0.6; margin-left: 0.5rem; }
  `],
})
export class AppComponent implements OnInit {
  private http = inject(HttpClient);

  users: User[] = [];
  loading = true;
  error: string | null = null;

  // ── Flag-driven state ─────────────────────────────────────────────────────
  flags: Partial<FeatureFlags> = {};
  darkMode          = getFlag('UI_DARK_MODE');
  maintenanceMode   = getFlag('CORE_MAINTENANCE_MODE');
  managerRoleEnabled = getFlag('USER_ROLE_MANAGER_ENABLED');
  quickActionsBar   = getFlag('UI_QUICK_ACTIONS_BAR');
  showAvatars       = getFlag('USER_PROFILE_PICTURE');

  readonly flagEffects: Partial<Record<keyof FeatureFlags, string>> = {
    CORE_MAINTENANCE_MODE:     'Red banner, disables write ops',
    USER_SELF_REGISTRATION:    'Show/hide Create User form (React)',
    USER_ROLE_MANAGER_ENABLED: 'Show/hide MANAGER rows in table',
    USER_PROFILE_PICTURE:      'Avatar initials in user rows',
    ORDER_BULK_OPERATIONS:     'Bulk-select column (React)',
    UI_DARK_MODE:              'Apply dark theme to root element',
    UI_NEW_DASHBOARD_LAYOUT:   'Card grid layout (React)',
    UI_QUICK_ACTIONS_BAR:      'Floating quick-actions toolbar',
  };

  get flagEntries(): { key: keyof FeatureFlags; value: boolean }[] {
    return (Object.entries(this.flags) as [keyof FeatureFlags, boolean][])
      .map(([key, value]) => ({ key, value }));
  }

  get filteredUsers(): User[] {
    return this.managerRoleEnabled
      ? this.users
      : this.users.filter(u => u.role !== UserRole.MANAGER);
  }

  get hiddenManagerCount(): number {
    return this.users.filter(u => u.role === UserRole.MANAGER).length;
  }

  ngOnInit(): void {
    this.loadFlags();
    this.loadUsers();
  }

  /** Fetch live flag values from api-gateway; fall through to static defaults on error. */
  loadFlags(): void {
    this.http.get<ApiResponse<FeatureFlags>>(`${API_BASE}/flags`).subscribe({
      next: res => {
        this.flags             = res.data;
        this.darkMode          = !!res.data.UI_DARK_MODE;
        this.maintenanceMode   = !!res.data.CORE_MAINTENANCE_MODE;
        this.managerRoleEnabled = res.data.USER_ROLE_MANAGER_ENABLED !== false;
        this.quickActionsBar   = !!res.data.UI_QUICK_ACTIONS_BAR;
        this.showAvatars       = !!res.data.USER_PROFILE_PICTURE;
      },
      error: () => {
        // Static compile-time fallback when gateway is unreachable
        this.flags = {};
      },
    });
  }

  loadUsers(): void {
    this.loading = true;
    this.error = null;
    this.http.get<ApiResponse<PaginatedResponse<User>>>(`${API_BASE}/users`).subscribe({
      next: res => {
        this.users = res.data.items;
        this.loading = false;
      },
      error: () => {
        this.error = 'Could not reach user-service (is api-gateway running on :3000?)';
        this.loading = false;
      },
    });
  }

  roleBadgeColor(role: UserRole): BadgeColor {
    const map: Record<UserRole, BadgeColor> = {
      [UserRole.ADMIN]:    'purple',
      [UserRole.MANAGER]:  'blue',
      [UserRole.CUSTOMER]: 'green',
    };
    return map[role] ?? 'gray';
  }

  statusLevel(status: UserStatus): StatusLevel {
    const map: Record<UserStatus, StatusLevel> = {
      [UserStatus.ACTIVE]:    'success',
      [UserStatus.SUSPENDED]: 'error',
      [UserStatus.INACTIVE]:  'neutral',
    };
    return map[status] ?? 'neutral';
  }
}
